[project]
name = "agent-world"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "numpy>=2.3.2",
    "pygame>=2.6.1",
    "rich>=14.2.0",
]

[tool.ruff.lint]
select = ["ALL"]
ignore = ["FIX002", "TD002"]

[tool.ruff]
line-length = 120
