[project]
name = "agent-world"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "numpy>=2.3.2",
    "pygame-ce>=2.5.6",
    "rich>=14.2.0",
]

[tool.ruff.lint]
select = ["ALL"]
ignore = ["FIX002", "TD002", "D203", "D213"]

[tool.ruff]
line-length = 120

[lint.isort]
required-imports = ["from __future__ import annotations"]

[dependency-groups]
dev = []

[tool.ruff.lint.isort]
required-imports = ["from __future__ import annotations"]
